### ISSUE TITLE
[request] Update to latest Vue version

### ISSUE THREAD

**Issue by nothingismagick** [Jinjiang/vue-a11y-utils#4]
Are there plans to update this to vue 2.6?

**Comment by Jinjiang** [comment]
Theoretically, it is compatible with Vue 2.6. I will make a quick check soon.
Thanks.

**Comment by Jinjiang** [comment]
https://jinjiang.github.io/vue-a11y-examples
All examples work in Vue 2.6. Seems OK. Feel free to recreate issue if any compatibility problem found.
Thanks.
